const menuItems = [
  // VEGETARIAN SNACKS
  { name: 'Veg Salad', category: 'Veg Snacks', price: 60, description: 'Fresh seasonal vegetable salad' },
  { name: 'Kaju Fry', category: 'Veg Snacks', price: 170, description: 'Crispy fried cashew nuts' },
  { name: 'Paneer 65', category: 'Veg Snacks', price: 230, description: 'Spicy and crispy fried paneer' },
  { name: 'Paneer Manchurian', category: 'Veg Snacks', price: 200, description: 'Paneer tossed in sweet and tangy sauce' },
  { name: 'Chilli Paneer', category: 'Veg Snacks', price: 200, description: 'Spicy paneer tossed with chilies' },
  { name: 'Mushroom 65', category: 'Veg Snacks', price: 220, description: 'Crispy fried mushrooms' },
  { name: 'Mushroom Fry', category: 'Veg Snacks', price: 180, description: 'Sautéed mushrooms with spices' },
  { name: 'Chilli Mushroom', category: 'Veg Snacks', price: 200, description: 'Mushrooms in spicy chili sauce' },
  { name: 'Crispy Corn', category: 'Veg Snacks', price: 130, description: 'Deep fried crispy sweet corn kernels' },
  { name: 'Fries', category: 'Veg Snacks', price: 150, description: 'Classic potato french fries' },
  { name: 'Boiled Palli', category: 'Veg Snacks', price: 80, description: 'Boiled peanuts' },
  { name: 'Boiled Palli Masala', category: 'Veg Snacks', price: 100, description: 'Boiled peanuts with spicy masala' },
  { name: 'Peanut Masala', category: 'Veg Snacks', price: 100, description: 'Spicy peanut mix' },
  { name: 'Gobi Manchuria', category: 'Veg Snacks', price: 180, description: 'Cauliflower florets in tangy sauce' },
  { name: 'Sweet Corn', category: 'Veg Snacks', price: 80, description: 'Steamed sweet corn' },

  // EGG & NON-VEG SNACKS
  { name: 'Chilli Egg', category: 'Non-Veg Snacks', price: 180, description: 'Spicy egg preparation' },
  { name: 'Egg Burji', category: 'Non-Veg Snacks', price: 120, description: 'Scrambled eggs with Indian spices' },
  { name: 'Egg Manchuriya', category: 'Non-Veg Snacks', price: 200, description: 'Egg chunks in Manchurian sauce' },
  { name: 'Boiled Egg', category: 'Non-Veg Snacks', price: 80, description: 'Classic boiled eggs' },
  { name: 'Egg Fry', category: 'Non-Veg Snacks', price: 130, description: 'Fried egg slices with spices' },
  { name: 'Omlette', category: 'Non-Veg Snacks', price: 80, description: 'Fluffy pan-fried beaten eggs' },
  { name: 'Mutton Ghee Roast', category: 'Non-Veg Snacks', price: 400, description: 'Mutton roasted in pure ghee with spices' },
  { name: 'Mutton Fry', category: 'Non-Veg Snacks', price: 350, description: 'Spicy fried mutton pieces' },
  { name: 'Dragon Chicken', category: 'Non-Veg Snacks', price: 300, description: 'Sweet and spicy Indo-Chinese chicken' },
  { name: 'Chicken Mangolian', category: 'Non-Veg Snacks', price: 320, description: 'Mongolian style savory chicken' },
  { name: 'Chicken Rajadhani', category: 'Non-Veg Snacks', price: 300, description: 'Special royal chicken starter' },
  { name: 'Chilli Chicken', category: 'Non-Veg Snacks', price: 250, description: 'Classic spicy chili chicken' },
  { name: 'Chicken Boneless Pakodi', category: 'Non-Veg Snacks', price: 250, description: 'Crispy chicken fritters' },
  { name: 'Chicken Manchuriya', category: 'Non-Veg Snacks', price: 250, description: 'Chicken in tangy Manchurian sauce' },
  { name: 'Chicken 555', category: 'Non-Veg Snacks', price: 250, description: 'Spicy deep-fried chicken strips' },
  { name: 'Chicken Majestic', category: 'Non-Veg Snacks', price: 280, description: 'Dry chicken strips tossed in yogurt and spices' },
  { name: 'Chicken 65', category: 'Non-Veg Snacks', price: 250, description: 'Spicy, deep-fried chicken' },
  { name: 'Chicken Lollypops', category: 'Non-Veg Snacks', price: 400, description: 'Fried chicken drumettes' },
  { name: 'Chicken Wings', category: 'Non-Veg Snacks', price: 300, description: 'Spicy and crispy chicken wings' },
  { name: 'Royal King', category: 'Non-Veg Snacks', price: 350, description: 'House special chicken starter' },
  { name: 'Chicken Ambhani', category: 'Non-Veg Snacks', price: 350, description: 'Richly flavored chicken bites' },
  { name: 'Pepper Chicken', category: 'Non-Veg Snacks', price: 280, description: 'Chicken dry roasted with black pepper' },

  // SEA FOOD
  { name: 'Apollo Fish', category: 'Sea Food', price: 350, description: 'Spicy batter-fried fish cubes' },
  { name: 'Prawn Kaju Fry', category: 'Sea Food', price: 350, description: 'Prawns fried with cashew nuts' },
  { name: 'Chilly Prawns', category: 'Sea Food', price: 350, description: 'Prawns tossed in spicy chili sauce' },
  { name: 'Fish Roast (4 Pcs)', category: 'Sea Food', price: 200, description: 'Spiced and roasted fish pieces' },
  { name: 'Loose Prawn', category: 'Sea Food', price: 350, description: 'Crispy golden fried prawns' },
  { name: 'Prawn Fry', category: 'Sea Food', price: 350, description: 'Spicy fried prawns' },

  // BIRYANI
  { name: 'SP Mushroom Biryani', category: 'Biryani', price: 280, description: 'Special mushroom flavored rice' },
  { name: 'Paneer Biryani', category: 'Biryani', price: 220, description: 'Aromatic rice with paneer cubes' },
  { name: 'Veg Biryani', category: 'Biryani', price: 200, description: 'Mixed vegetable fragrant rice' },
  { name: 'Rambo Chicken Biryani', category: 'Biryani', price: 300, description: 'House special Rambo chicken biryani' },
  { name: 'Chicken Dum Biryani', category: 'Biryani', price: 240, description: 'Classic slow-cooked chicken biryani' },
  { name: 'Chicken Fry Piece Biryani', category: 'Biryani', price: 280, description: 'Biryani rice served with fried chicken pieces' },
  { name: 'Chicken Lollypop Biryani', category: 'Biryani', price: 300, description: 'Biryani topped with chicken lollipops' },
  { name: 'Chicken Wings Biryani', category: 'Biryani', price: 300, description: 'Fragrant rice with spicy chicken wings' },
  { name: 'Mutton Dum Biryani', category: 'Biryani', price: 400, description: 'Slow-cooked aromatic mutton biryani' },
  { name: 'Mutton Fry Piece Biryani', category: 'Biryani', price: 400, description: 'Biryani rice with fried mutton' },
  { name: 'Prawn Biryani', category: 'Biryani', price: 400, description: 'Spicy and flavorful prawn biryani' },
  { name: 'Mixed Biryani', category: 'Biryani', price: 400, description: 'Biryani with a mix of meats' },
  { name: 'Mughlai Biryani', category: 'Biryani', price: 300, description: 'Rich and creamy Mughlai style biryani' },

  // CURRIES
  { name: 'Paneer Butter Masala', category: 'Curries', price: 200, description: 'Paneer in rich tomato buttery gravy' },
  { name: 'Tomato Kaju Curry', category: 'Curries', price: 250, description: 'Cashews in tangy tomato gravy' },
  { name: 'Methi Chaman', category: 'Curries', price: 200, description: 'Paneer with fresh fenugreek leaves' },
  { name: 'Kaju Paneer', category: 'Curries', price: 240, description: 'Paneer and cashews in rich gravy' },
  { name: 'Malai Kofta', category: 'Curries', price: 260, description: 'Cottage cheese dumplings in creamy sauce' },
  { name: 'Mixed Veg Curry', category: 'Curries', price: 160, description: 'Assorted vegetables in spiced gravy' },
  { name: 'Andhra Chicken', category: 'Curries', price: 260, description: 'Spicy traditional Andhra style chicken curry' },
  { name: 'Boneless Chicken Curry', category: 'Curries', price: 260, description: 'Tender boneless chicken in gravy' },
  { name: 'Mutton Gravy Curry', category: 'Curries', price: 350, description: 'Rich and spicy mutton gravy' },
  { name: 'Gongura Chicken Curry', category: 'Curries', price: 260, description: 'Chicken cooked with tangy sorrel leaves' },
  { name: 'Chicken Maharani', category: 'Curries', price: 300, description: 'Royal creamy chicken curry' },
  { name: 'Gongura Mutton Curry', category: 'Curries', price: 350, description: 'Mutton cooked with tangy sorrel leaves' },
  { name: 'Mogalai Chicken Curry', category: 'Curries', price: 260, description: 'Rich Mughlai style chicken curry' },
  { name: 'Kadai Chicken', category: 'Curries', price: 300, description: 'Chicken cooked in a wok with bell peppers' },
  { name: 'Fish Curry', category: 'Curries', price: 250, description: 'Traditional homestyle fish curry' },
  { name: 'Prawns Curry', category: 'Curries', price: 350, description: 'Spicy prawn gravy' },

  // RICE & BREADS
  { name: 'Chicken Schezwan Fried Rice', category: 'Rice & Breads', price: 300, description: 'Spicy Schezwan style chicken fried rice' },
  { name: 'Chicken Singapoor Fried Rice', category: 'Rice & Breads', price: 300, description: 'Singapore style chicken fried rice' },
  { name: 'Egg Fried Rice', category: 'Rice & Breads', price: 180, description: 'Fried rice tossed with eggs' },
  { name: 'Chicken Fried Rice', category: 'Rice & Breads', price: 200, description: 'Classic chicken fried rice' },
  { name: 'Veg Fried Rice', category: 'Rice & Breads', price: 160, description: 'Mixed vegetable fried rice' },
  { name: 'Jeera Rice', category: 'Rice & Breads', price: 180, description: 'Cumin flavored rice' },
  { name: 'Curd Rice', category: 'Rice & Breads', price: 100, description: 'Yogurt mixed with rice and tempered spices' },
  { name: 'Paneer Fried Rice', category: 'Rice & Breads', price: 230, description: 'Fried rice with paneer cubes' },
  { name: 'Mushroom Fried Rice', category: 'Rice & Breads', price: 230, description: 'Fried rice with mushrooms' },
  { name: 'Kaju Fried Rice', category: 'Rice & Breads', price: 260, description: 'Fried rice with roasted cashews' },
  { name: 'White Rice', category: 'Rice & Breads', price: 60, description: 'Steamed plain rice' },
  { name: 'Pulka', category: 'Rice & Breads', price: 10, description: 'Soft Indian flatbread' }
].map((item, index) => ({ ...item, _id: (index + 1).toString() }));

module.exports = menuItems;
